### PR TITLE
Add Drawer and Fix Navbar

### LINKED ISSUE #24: Navbar Mobile
## Overview 
We need to have the mobile hamburger menu button work such that clicking on it will make a drawer appear from the right side. The navbar's mobile view also needs to be fixed. It got messed up since we did not have ChakraProvider in our app before, but now we do. 

### Week 1 (Fall W1)
- Create a new component for the hamburger button so we can have the entire mobile menu in there 
   - Refer to the [Chakra Drawer Docs](https://chakra-ui.com/docs/components/drawer)
   - Don't worry too much of how the mobile drawer menu looks, just try to get it to work (Design team needs to finalize design I believe) 
- For the mobile view of the navbar try playing around with [relative units](https://gist.github.com/basham/2175a16ab7c60ce8e001)
   - We may want to replace the navbar layout with a [flex layout](https://chakra-ui.com/docs/components/flex) 
   - Flexbox is annoying but once you get the hang of it it makes a lot of things easier!

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #24

### CODE REVIEW

**Comment by Madhu2244** [comment]
hello, please take a look at the figma that was made just now here: https://www.figma.com/file/7eBxLZEstTe8Gtuo2Rduio/Dev-Ready-Components?node-id=404%3A3852&t=u7rkh68GJWTZ8J15-0

also if you can make the buttons on the navbar a bit smaller cuz some of them r massive in mobile view. that would really help!

File: src/components/Navbar.jsx [hunk 1]
```diff
@@ -1,89 +1,126 @@
...
-                <img src={cellDogsSampleProfilePicture} alt="Cell Dogs Sample Profile" />
-                <div className="profile-text">
-                  <p className="profile-name">Rayvan Dog</p>
-                  <p className="profile-role">Developer</p>
-                </div>
-              </button>
+
+            <div className="navbar-right">
+              <div className="navbar-icon">
+                <button type="button" onClick={() => alert('Navbar Icon 1 Button Clicked')}>
```
Comment (ctc-devops) [inline src/components/Navbar.jsx:52]: ⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

File: src/components/Navbar.jsx [hunk 2]
```diff
@@ -2,88 +1,126 @@
...
+                  <QuestionOutlineIcon w="1.75em" h="1.75em" />
+                </button>
+              </div>
+              <div className="navbar-icon">
+                <button
+                  type="button"
+                  className="navbar-icon"
+                  onClick={() => alert('Navbar Icon 2 Button Clicked')}
```
Comment (ctc-devops) [inline src/components/Navbar.jsx:60]: ⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

File: src/components/Navbar.jsx [hunk 3]
```diff
@@ -2,88 +1,126 @@
...
+                >
+                  <BsFillPersonPlusFill size={28} />
+                </button>
+              </div>
+              <div className="navbar-user-profile">
+                <button type="button" onClick={() => alert('User Profile Button Clicked')}>
```
Comment (ctc-devops) [inline src/components/Navbar.jsx:66]: ⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

File: src/components/Navbar.jsx [hunk 4]
```diff
@@ -2,88 +1,126 @@
...
+            />
+          </div>
+          <div className="cell-dogs-logo">
+            <NavLink to="/">
+              <img src={cellDogsLogoHorizontal2} alt="Cell Dogs Logo Horizontal 2" />
+            </NavLink>
           </div>
+          <div className="navbar-right-short">
+            <div className="navbar-icon">
+              <button type="button" onClick={() => alert('Navbar Icon 2 Button Clicked')}>
```
Comment (ctc-devops) [inline src/components/Navbar.jsx:94]: ⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

**Review by Madhu2244 — APPROVED** [review]
